name: CI (smoke)
on:
  pull_request:
    branches: [ main ]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Smoke check
        run: |
          test -f index.html || (echo "index.html missing"; exit 1)
          echo "OK"
