name: CI (smoke)

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Print Node versions
        run: |
          node -v
          npm -v

      # --- JS構文チェック（落ちたら赤止め） ---
      - name: Syntax check core
        run: npx --yes acorn --ecma2022 --module js/player.core.js

      - name: Syntax check tts-kv-simple
        run: |
          if [ -f js/tts-kv-simple.js ]; then
            npx --yes acorn --ecma2022 --module js/tts-kv-simple.js
          else
            echo "js/tts-kv-simple.js not present (optional)."
          fi

      # --- 任意の辞書JSONがある場合は JSON.parse 検査 ---
      - name: Validate assets/tts-rules.json (optional)
        run: |
          if [ -f assets/tts-rules.json ]; then
            node -e "const fs=require('fs'); JSON.parse(fs.readFileSync('assets/tts-rules.json','utf8')); console.log('assets/tts-rules.json OK');"
          else
            echo "assets/tts-rules.json not present (optional)."
          fi

      # --- 必須ファイルの存在チェック ---
      - name: Static assets presence
        run: |
          test -f index.html
          test -f scenes.json
          test -f js/player.core.js
          echo "required files present"